### pandas: Детали (Часть 2) [Домашнее задание]
> **Вы должны импортировать все необходимые пакеты самостоятельно.**

> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**
 

### Шаг 1

Пожалуйста, напишите функцию ```load_data(filename)```, которая будет загружать данные из csv-файла в список списков. Пожалуйста, напишите функцию ```load_data(filename)```, которая будет загружать данные из csv-файла в ```DataFrame```. Файл ```clean_house_prices.csv``` предоставлен вместе с этим jupyter notebook.


**Примечание:**

* В случае, если имя файла задано неверно, функция ```load_data``` должна вывести следующее сообщение об ошибке:

```{имя файла} does not exist```
* ```clean_house_prices.csv``` - это csv-файл, который является результатом вашей предыдущей домашней работы.

In [1]:
#Начало вашего кода
import csv
import pandas as pd
import numpy as np
import os.path
def load_data(filename):
    list_i=[]
    if os.path.exists(filename)!=True:
        print(f"{filename} does not exist")
    else:
        with open(filename) as new_file:
            data=pd.read_csv(new_file)
        return data
#Конец вашего кода

In [2]:
filename = "./SocialNetworkAds.csv"
data = load_data(filename=filename)

./SocialNetworkAds.csv does not exist


### Ожидаемый результат:

```
./SocialNetworkAds.csv does not exist
```

In [3]:
print(data)

None


### Ожидаемый результат:

```
None
```

In [4]:
filename = "./clean_house_prices.csv"
data = load_data(filename=filename)

In [5]:
print(data.columns.values)

['Id' 'MSSubClass' 'MSZoning' 'LotArea' 'Street' 'LotShape' 'LandContour'
 'Utilities' 'LotConfig' 'LandSlope' 'Neighborhood' 'Condition1'
 'Condition2' 'BldgType' 'HouseStyle' 'OverallQual' 'OverallCond'
 'YearBuilt' 'YearRemodAdd' 'RoofStyle' 'RoofMatl' 'Exterior1st'
 'Exterior2nd' 'MasVnrType' 'MasVnrArea' 'ExterQual' 'ExterCond'
 'Foundation' 'BsmtQual' 'BsmtCond' 'BsmtExposure' 'BsmtFinType1'
 'BsmtFinSF1' 'BsmtFinType2' 'BsmtFinSF2' 'BsmtUnfSF' 'TotalBsmtSF'
 'Heating' 'HeatingQC' 'CentralAir' 'Electrical' '1stFlrSF' '2ndFlrSF'
 'LowQualFinSF' 'GrLivArea' 'BsmtFullBath' 'BsmtHalfBath' 'FullBath'
 'HalfBath' 'BedroomAbvGr' 'KitchenAbvGr' 'KitchenQual' 'TotRmsAbvGrd'
 'Functional' 'Fireplaces' 'GarageType' 'GarageYrBlt' 'GarageFinish'
 'GarageCars' 'GarageArea' 'GarageQual' 'GarageCond' 'PavedDrive'
 'WoodDeckSF' 'OpenPorchSF' 'EnclosedPorch' '3SsnPorch' 'ScreenPorch'
 'PoolArea' 'MiscVal' 'MoSold' 'YrSold' 'SaleType' 'SaleCondition'
 'SalePrice']


### Ожидаемый результат:

```
['Id' 'MSSubClass' 'MSZoning' 'LotArea' 'Street' 'LotShape' 'LandContour'
 'Utilities' 'LotConfig' 'LandSlope' 'Neighborhood' 'Condition1'
 'Condition2' 'BldgType' 'HouseStyle' 'OverallQual' 'OverallCond'
 'YearBuilt' 'YearRemodAdd' 'RoofStyle' 'RoofMatl' 'Exterior1st'
 'Exterior2nd' 'MasVnrType' 'MasVnrArea' 'ExterQual' 'ExterCond'
 'Foundation' 'BsmtQual' 'BsmtCond' 'BsmtExposure' 'BsmtFinType1'
 'BsmtFinSF1' 'BsmtFinType2' 'BsmtFinSF2' 'BsmtUnfSF' 'TotalBsmtSF'
 'Heating' 'HeatingQC' 'CentralAir' 'Electrical' '1stFlrSF' '2ndFlrSF'
 'LowQualFinSF' 'GrLivArea' 'BsmtFullBath' 'BsmtHalfBath' 'FullBath'
 'HalfBath' 'BedroomAbvGr' 'KitchenAbvGr' 'KitchenQual' 'TotRmsAbvGrd'
 'Functional' 'Fireplaces' 'GarageType' 'GarageYrBlt' 'GarageFinish'
 'GarageCars' 'GarageArea' 'GarageQual' 'GarageCond' 'PavedDrive'
 'WoodDeckSF' 'OpenPorchSF' 'EnclosedPorch' '3SsnPorch' 'ScreenPorch'
 'PoolArea' 'MiscVal' 'MoSold' 'YrSold' 'SaleType' 'SaleCondition'
 'SalePrice']
```

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1338 non-null   int64  
 1   MSSubClass     1338 non-null   int64  
 2   MSZoning       1338 non-null   object 
 3   LotArea        1338 non-null   int64  
 4   Street         1338 non-null   object 
 5   LotShape       1338 non-null   object 
 6   LandContour    1338 non-null   object 
 7   Utilities      1338 non-null   object 
 8   LotConfig      1338 non-null   object 
 9   LandSlope      1338 non-null   object 
 10  Neighborhood   1338 non-null   object 
 11  Condition1     1338 non-null   object 
 12  Condition2     1338 non-null   object 
 13  BldgType       1338 non-null   object 
 14  HouseStyle     1338 non-null   object 
 15  OverallQual    1338 non-null   int64  
 16  OverallCond    1338 non-null   int64  
 17  YearBuilt      1338 non-null   int64  
 18  YearRemo

### Ожидаемый результат:

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 75 columns):
Id               1338 non-null int64
MSSubClass       1338 non-null int64
MSZoning         1338 non-null object
LotArea          1338 non-null int64
Street           1338 non-null object
LotShape         1338 non-null object
LandContour      1338 non-null object
Utilities        1338 non-null object
LotConfig        1338 non-null object
LandSlope        1338 non-null object
Neighborhood     1338 non-null object
Condition1       1338 non-null object
Condition2       1338 non-null object
BldgType         1338 non-null object
HouseStyle       1338 non-null object
OverallQual      1338 non-null int64
OverallCond      1338 non-null int64
YearBuilt        1338 non-null int64
YearRemodAdd     1338 non-null int64
RoofStyle        1338 non-null object
RoofMatl         1338 non-null object
Exterior1st      1338 non-null object
Exterior2nd      1338 non-null object
MasVnrType       1338 non-null object
MasVnrArea       1338 non-null float64
ExterQual        1338 non-null object
ExterCond        1338 non-null object
Foundation       1338 non-null object
BsmtQual         1338 non-null object
BsmtCond         1338 non-null object
BsmtExposure     1338 non-null object
BsmtFinType1     1338 non-null object
BsmtFinSF1       1338 non-null int64
BsmtFinType2     1338 non-null object
BsmtFinSF2       1338 non-null int64
BsmtUnfSF        1338 non-null int64
TotalBsmtSF      1338 non-null int64
Heating          1338 non-null object
HeatingQC        1338 non-null object
CentralAir       1338 non-null object
Electrical       1338 non-null object
1stFlrSF         1338 non-null int64
2ndFlrSF         1338 non-null int64
LowQualFinSF     1338 non-null int64
GrLivArea        1338 non-null int64
BsmtFullBath     1338 non-null int64
BsmtHalfBath     1338 non-null int64
FullBath         1338 non-null int64
HalfBath         1338 non-null int64
BedroomAbvGr     1338 non-null int64
KitchenAbvGr     1338 non-null int64
KitchenQual      1338 non-null object
TotRmsAbvGrd     1338 non-null int64
Functional       1338 non-null object
Fireplaces       1338 non-null int64
GarageType       1338 non-null object
GarageYrBlt      1338 non-null float64
GarageFinish     1338 non-null object
GarageCars       1338 non-null int64
GarageArea       1338 non-null int64
GarageQual       1338 non-null object
GarageCond       1338 non-null object
PavedDrive       1338 non-null object
WoodDeckSF       1338 non-null int64
OpenPorchSF      1338 non-null int64
EnclosedPorch    1338 non-null int64
3SsnPorch        1338 non-null int64
ScreenPorch      1338 non-null int64
PoolArea         1338 non-null int64
MiscVal          1338 non-null int64
MoSold           1338 non-null int64
YrSold           1338 non-null int64
SaleType         1338 non-null object
SaleCondition    1338 non-null object
SalePrice        1338 non-null int64
dtypes: float64(2), int64(35), object(38)
memory usage: 784.1+ KB
```

In [7]:
print(data.describe())

                Id   MSSubClass        LotArea  OverallQual  OverallCond  \
count  1338.000000  1338.000000    1338.000000  1338.000000  1338.000000   
mean    731.228700    56.136024   10706.294469     6.219731     5.596413   
std     421.779691    41.252576   10336.621126     1.324472     1.078124   
min       1.000000    20.000000    1300.000000     2.000000     2.000000   
25%     366.250000    20.000000    7744.000000     5.000000     5.000000   
50%     730.500000    50.000000    9600.000000     6.000000     5.000000   
75%    1098.750000    70.000000   11760.750000     7.000000     6.000000   
max    1460.000000   190.000000  215245.000000    10.000000     9.000000   

         YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1   BsmtFinSF2  ...  \
count  1338.000000   1338.000000  1338.000000  1338.000000  1338.000000  ...   
mean   1973.029148   1985.668909   110.360239   464.234679    49.218236  ...   
std      29.563540     20.296463   185.604816   458.792420   166.196584  ..

### Ожидаемый результат:

```
                Id   MSSubClass        LotArea  OverallQual  OverallCond  \
count  1338.000000  1338.000000    1338.000000  1338.000000  1338.000000   
mean    731.228700    56.136024   10706.294469     6.219731     5.596413   
std     421.779691    41.252576   10336.621126     1.324472     1.078124   
min       1.000000    20.000000    1300.000000     2.000000     2.000000   
25%     366.250000    20.000000    7744.000000     5.000000     5.000000   
50%     730.500000    50.000000    9600.000000     6.000000     5.000000   
75%    1098.750000    70.000000   11760.750000     7.000000     6.000000   
max    1460.000000   190.000000  215245.000000    10.000000     9.000000   

         YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1   BsmtFinSF2  ...  \
count  1338.000000   1338.000000  1338.000000  1338.000000  1338.000000  ...   
mean   1973.029148   1985.668909   110.360239   464.234679    49.218236  ...   
std      29.563540     20.296463   185.604816   458.792420   166.196584  ...   
min    1880.000000   1950.000000     0.000000     0.000000     0.000000  ...   
25%    1956.000000   1968.000000     0.000000     0.000000     0.000000  ...   
50%    1976.000000   1994.500000     0.000000   413.000000     0.000000  ...   
75%    2001.000000   2004.000000   174.000000   733.000000     0.000000  ...   
max    2010.000000   2010.000000  1600.000000  5644.000000  1474.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1338.000000  1338.000000    1338.000000  1338.000000   1338.00000   
mean     99.384903    47.782511      21.263827     3.585949     16.43423   
std     127.537065    65.362562      60.843964    30.224622     58.05159   
min       0.000000     0.000000       0.000000     0.000000      0.00000   
25%       0.000000     0.000000       0.000000     0.000000      0.00000   
50%       6.000000    28.000000       0.000000     0.000000      0.00000   
75%     174.500000    70.000000       0.000000     0.000000      0.00000   
max     857.000000   547.000000     552.000000   508.000000    480.00000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1338.000000   1338.000000  1338.000000  1338.000000    1338.000000  
mean      3.010463     42.932735     6.331839  2007.805680  186761.782511  
std      41.961337    508.056255     2.699437     1.330691   78913.847668  
min       0.000000      0.000000     1.000000  2006.000000   35311.000000  
25%       0.000000      0.000000     5.000000  2007.000000  135000.000000  
50%       0.000000      0.000000     6.000000  2008.000000  168500.000000  
75%       0.000000      0.000000     8.000000  2009.000000  220000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 37 columns]
```

**Распечатайте первые и последние 5 строк pandas.DataFrame:**

In [8]:
#Начало вашего кода
print(data.head())
print(data.tail())
#Конец вашего кода

   Id  MSSubClass MSZoning  LotArea Street LotShape LandContour Utilities  \
0   1          60       RL     8450   Pave      Reg         Lvl    AllPub   
1   2          20       RL     9600   Pave      Reg         Lvl    AllPub   
2   3          60       RL    11250   Pave      IR1         Lvl    AllPub   
3   4          70       RL     9550   Pave      IR1         Lvl    AllPub   
4   5          60       RL    14260   Pave      IR1         Lvl    AllPub   

  LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch PoolArea  \
0    Inside       Gtl  ...             0         0           0        0   
1       FR2       Gtl  ...             0         0           0        0   
2    Inside       Gtl  ...             0         0           0        0   
3    Corner       Gtl  ...           272         0           0        0   
4       FR2       Gtl  ...             0         0           0        0   

  MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0       0       2    20

### Ожидаемый результат:

```
   Id  MSSubClass MSZoning  LotArea Street LotShape LandContour Utilities  \
0   1          60       RL     8450   Pave      Reg         Lvl    AllPub   
1   2          20       RL     9600   Pave      Reg         Lvl    AllPub   
2   3          60       RL    11250   Pave      IR1         Lvl    AllPub   
3   4          70       RL     9550   Pave      IR1         Lvl    AllPub   
4   5          60       RL    14260   Pave      IR1         Lvl    AllPub   

  LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch PoolArea  \
0    Inside       Gtl  ...             0         0           0        0   
1       FR2       Gtl  ...             0         0           0        0   
2    Inside       Gtl  ...             0         0           0        0   
3    Corner       Gtl  ...           272         0           0        0   
4       FR2       Gtl  ...             0         0           0        0   

  MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0       0       2    2008        WD         Normal    208500  
1       0       5    2007        WD         Normal    181500  
2       0       9    2008        WD         Normal    223500  
3       0       2    2006        WD        Abnorml    140000  
4       0      12    2008        WD         Normal    250000  

[5 rows x 75 columns]
        Id  MSSubClass MSZoning  LotArea Street LotShape LandContour  \
1333  1456          60       RL     7917   Pave      Reg         Lvl   
1334  1457          20       RL    13175   Pave      Reg         Lvl   
1335  1458          70       RL     9042   Pave      Reg         Lvl   
1336  1459          20       RL     9717   Pave      Reg         Lvl   
1337  1460          20       RL     9937   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
1333    AllPub    Inside       Gtl  ...             0         0           0   
1334    AllPub    Inside       Gtl  ...             0         0           0   
1335    AllPub    Inside       Gtl  ...             0         0           0   
1336    AllPub    Inside       Gtl  ...           112         0           0   
1337    AllPub    Inside       Gtl  ...             0         0           0   

     PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
1333        0       0       8    2007        WD         Normal    175000  
1334        0       0       2    2010        WD         Normal    210000  
1335        0    2500       5    2010        WD         Normal    266500  
1336        0       0       4    2010        WD         Normal    142125  
1337        0       0       6    2008        WD         Normal    147500  

[5 rows x 75 columns]
```

### Шаг 2

Запустите приведенный ниже блок кода и попытайтесь получить представление о данных, которые вы просматриваете.


In [9]:
pd_data=data.copy()
pd_data.set_index("Id",inplace=True)
pd_data

MSSubClass MSZoning  LotArea Street LotShape LandContour Utilities  \
Id                                                                         
1             60       RL     8450   Pave      Reg         Lvl    AllPub   
2             20       RL     9600   Pave      Reg         Lvl    AllPub   
3             60       RL    11250   Pave      IR1         Lvl    AllPub   
4             70       RL     9550   Pave      IR1         Lvl    AllPub   
5             60       RL    14260   Pave      IR1         Lvl    AllPub   
...          ...      ...      ...    ...      ...         ...       ...   
1456          60       RL     7917   Pave      Reg         Lvl    AllPub   
1457          20       RL    13175   Pave      Reg         Lvl    AllPub   
1458          70       RL     9042   Pave      Reg         Lvl    AllPub   
1459          20       RL     9717   Pave      Reg         Lvl    AllPub   
1460          20       RL     9937   Pave      Reg         Lvl    AllPub   

     LotConfig LandSlope Neighborhood  ... EnclosedPorch 3SsnPorch  \
Id                                     ...                           
1       Inside       Gtl      CollgCr  ...             0         0   
2          FR2       Gtl      Veenker  ...             0         0   
3       Inside       Gtl      CollgCr  ...             0         0   
4       Corner       Gtl      Crawfor  ...           272         0   
5          FR2       Gtl      NoRidge  ...             0         0   
...        ...       ...          ...  ...           ...       ...   
1456    Inside       Gtl      Gilbert  ...             0         0   
1457    Inside       Gtl       NWAmes  ...             0         0   
1458    Inside       Gtl      Crawfor  ...             0         0   
1459    Inside       Gtl        NAmes  ...           112         0   
1460    Inside       Gtl      Edwards  ...             0         0   

     ScreenPorch PoolArea  MiscVal  MoSold  YrSold  SaleType SaleCondition  \
Id                                                                           
1              0        0        0       2    2008        WD        Normal   
2              0        0        0       5    2007        WD        Normal   
3              0        0        0       9    2008        WD        Normal   
4              0        0        0       2    2006        WD       Abnorml   
5              0        0        0      12    2008        WD        Normal   
...          ...      ...      ...     ...     ...       ...           ...   
1456           0        0        0       8    2007        WD        Normal   
1457           0        0        0       2    2010        WD        Normal   
1458           0        0     2500       5    2010        WD        Normal   
1459           0        0        0       4    2010        WD        Normal   
1460           0        0        0       6    2008        WD        Normal   

     SalePrice  
Id              
1       208500  
2       181500  
3       223500  
4       140000  
5       250000  
...        ...  
1456    175000  
1457    210000  
1458    266500  
1459    142125  
1460    147500  

[1338 rows x 74 columns]

In [10]:
pd_data.dtypes

MSSubClass        int64
MSZoning         object
LotArea           int64
Street           object
LotShape         object
                  ...  
MoSold            int64
YrSold            int64
SaleType         object
SaleCondition    object
SalePrice         int64
Length: 74, dtype: object

Пожалуйста, реализуйте функцию ```split_str nums(date)```, которая возвращает один ```DataFrame```, содержащий **не числовые** элементы, и второй ```DataFrame``` **только с числовыми** элементами.

In [11]:
#Начало вашего кода
def split_str_nums(data):
    list_str=[]
    list_int=[]
    for i in data:
        if data[i].dtype=="object":
            list_str.append(data[i].name)
            str_data=data[list_str]
        else:
            list_int.append(data[i].name)
            num_data=data[list_int]
    return str_data,num_data
#Конец вашего кода
str_data,num_data=split_str_nums(pd_data)

In [12]:
print(str_data)

     MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
Id                                                                        
1          RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
2          RL   Pave      Reg         Lvl    AllPub       FR2       Gtl   
3          RL   Pave      IR1         Lvl    AllPub    Inside       Gtl   
4          RL   Pave      IR1         Lvl    AllPub    Corner       Gtl   
5          RL   Pave      IR1         Lvl    AllPub       FR2       Gtl   
...       ...    ...      ...         ...       ...       ...       ...   
1456       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1457       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1458       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1459       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1460       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   

     Neighborhood Condit

### Ожидаемый результат:

```
     MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
Id                                                                        
1          RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
2          RL   Pave      Reg         Lvl    AllPub       FR2       Gtl   
3          RL   Pave      IR1         Lvl    AllPub    Inside       Gtl   
4          RL   Pave      IR1         Lvl    AllPub    Corner       Gtl   
5          RL   Pave      IR1         Lvl    AllPub       FR2       Gtl   
...       ...    ...      ...         ...       ...       ...       ...   
1456       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1457       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1458       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1459       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1460       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   

     Neighborhood Condition1 Condition2  ... Electrical KitchenQual  \
Id                                       ...                          
1         CollgCr       Norm       Norm  ...      SBrkr          Gd   
2         Veenker      Feedr       Norm  ...      SBrkr          TA   
3         CollgCr       Norm       Norm  ...      SBrkr          Gd   
4         Crawfor       Norm       Norm  ...      SBrkr          Gd   
5         NoRidge       Norm       Norm  ...      SBrkr          Gd   
...           ...        ...        ...  ...        ...         ...   
1456      Gilbert       Norm       Norm  ...      SBrkr          TA   
1457       NWAmes       Norm       Norm  ...      SBrkr          TA   
1458      Crawfor       Norm       Norm  ...      SBrkr          Gd   
1459        NAmes       Norm       Norm  ...      FuseA          Gd   
1460      Edwards       Norm       Norm  ...      SBrkr          TA   

     Functional GarageType GarageFinish GarageQual GarageCond PavedDrive  \
Id                                                                         
1           Typ     Attchd          RFn         TA         TA          Y   
2           Typ     Attchd          RFn         TA         TA          Y   
3           Typ     Attchd          RFn         TA         TA          Y   
4           Typ     Detchd          Unf         TA         TA          Y   
5           Typ     Attchd          RFn         TA         TA          Y   
...         ...        ...          ...        ...        ...        ...   
1456        Typ     Attchd          RFn         TA         TA          Y   
1457       Min1     Attchd          Unf         TA         TA          Y   
1458        Typ     Attchd          RFn         TA         TA          Y   
1459        Typ     Attchd          Unf         TA         TA          Y   
1460        Typ     Attchd          Fin         TA         TA          Y   

     SaleType SaleCondition  
Id                           
1          WD        Normal  
2          WD        Normal  
3          WD        Normal  
4          WD       Abnorml  
5          WD        Normal  
...       ...           ...  
1456       WD        Normal  
1457       WD        Normal  
1458       WD        Normal  
1459       WD        Normal  
1460       WD        Normal  

[1338 rows x 38 columns]
```

In [13]:
print(num_data)

      MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
Id                                                                             
1             60     8450            7            5       2003          2003   
2             20     9600            6            8       1976          1976   
3             60    11250            7            5       2001          2002   
4             70     9550            7            5       1915          1970   
5             60    14260            8            5       2000          2000   
...          ...      ...          ...          ...        ...           ...   
1456          60     7917            6            5       1999          2000   
1457          20    13175            6            6       1978          1988   
1458          70     9042            7            9       1941          2006   
1459          20     9717            5            6       1950          1996   
1460          20     9937            5  

### Ожидаемый результат:

```
      MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
Id                                                                             
1             60     8450            7            5       2003          2003   
2             20     9600            6            8       1976          1976   
3             60    11250            7            5       2001          2002   
4             70     9550            7            5       1915          1970   
5             60    14260            8            5       2000          2000   
...          ...      ...          ...          ...        ...           ...   
1456          60     7917            6            5       1999          2000   
1457          20    13175            6            6       1978          1988   
1458          70     9042            7            9       1941          2006   
1459          20     9717            5            6       1950          1996   
1460          20     9937            5            6       1965          1965   

      MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  ...  WoodDeckSF  \
Id                                                   ...               
1          196.0         706           0        150  ...           0   
2            0.0         978           0        284  ...         298   
3          162.0         486           0        434  ...           0   
4            0.0         216           0        540  ...           0   
5          350.0         655           0        490  ...         192   
...          ...         ...         ...        ...  ...         ...   
1456         0.0           0           0        953  ...           0   
1457       119.0         790         163        589  ...         349   
1458         0.0         275           0        877  ...           0   
1459         0.0          49        1029          0  ...         366   
1460         0.0         830         290        136  ...         736   

      OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  MiscVal  \
Id                                                                            
1              61              0          0            0         0        0   
2               0              0          0            0         0        0   
3              42              0          0            0         0        0   
4              35            272          0            0         0        0   
5              84              0          0            0         0        0   
...           ...            ...        ...          ...       ...      ...   
1456           40              0          0            0         0        0   
1457            0              0          0            0         0        0   
1458           60              0          0            0         0     2500   
1459            0            112          0            0         0        0   
1460           68              0          0            0         0        0   

      MoSold  YrSold  SalePrice  
Id                               
1          2    2008     208500  
2          5    2007     181500  
3          9    2008     223500  
4          2    2006     140000  
5         12    2008     250000  
...      ...     ...        ...  
1456       8    2007     175000  
1457       2    2010     210000  
1458       5    2010     266500  
1459       4    2010     142125  
1460       6    2008     147500  

[1338 rows x 36 columns]
```

### Шаг 3

Как видно из данных, в некоторых столбцах много повторений. Пожалуйста, реализуйте функцию ```count_values(data, column)```, которая будет подсчитывать количество повторений для определенного столбца во входном аргументе ```data```.

Эта функция должна обрабатывать следующие случаи:
* если входной аргумент ```data``` пуст, выведите ошибку и верните пустой ```DataFrame```.
* если входной аргумент ```column``` имеет тип ```str```, верните ```DataFrame``` с результатами подсчета повторных значений для данного столбца во входном аргументе `` `data```.
* если входной аргумент ```column``` имеет тип ```list```, верните ```DataFrame``` с количеством повторных значений результатов для указанных столбцов из входного аргумента ```data```.
* если входной аргумент ```column``` пуст, верните ```DataFrame``` с количеством повторных значений результатов для всех столбцов из входного аргумента ```data```.


```DataFrame```, возвращаемый функцией, должен быть отсортирован в порядке убывания.


In [20]:
#Начало вашего кода
def count_values(data=None, column=None):
    pd_emp=pd.DataFrame()
    col_list=data.columns.tolist()
    
    if column!= None and str() in column:
        data_v=data[column].value_counts()
        pf_data=pd.DataFrame([data_v])
        t_pd=pf_data.T
        t_pd.columns=(["frequency"])
        sorted_data1=t_pd.sort_values(["frequency"],ascending=False)
        return sorted_data1
    
    else:
        if data is None:
            print("Error: data is empty")
            pd_emp=pd.DataFrame({})
            return pd_emp
        elif column!= None and str() not in column:
            columns=column
        elif column is None:
            columns=col_list
        for i in range(len(columns)):
            data_v=data[columns[i]].value_counts()
            pf_data2=pd.DataFrame([data_v])
            t_pd2=pf_data2.T
            t_pd2.columns=(["frequency"])
            sorted_data2=t_pd2.sort_values(["frequency"],ascending=False)
            pd_emp=pd.concat([pd_emp,sorted_data2],axis=0)
            pd_emp = pd_emp.astype(float)
        return pd_emp

    #Конец вашего кода

In [21]:
print(count_values(data=str_data))

         frequency
RL          1066.0
RM           191.0
FV            62.0
RH            11.0
C (all)        8.0
...            ...
Partial      120.0
Abnorml       86.0
Family        20.0
Alloca         7.0
AdjLand        1.0

[229 rows x 1 columns]


### Ожидаемый результат:

```
         frequency
RL          1066.0
RM           191.0
FV            62.0
RH            11.0
C (all)        8.0
...            ...
Partial      120.0
Abnorml       86.0
Family        20.0
Alloca         7.0
AdjLand        1.0

[229 rows x 1 columns]
```

In [22]:
print(count_values(data=str_data,column="Condition1"))

        frequency
Norm         1162
Feedr          63
Artery         43
RRAn           26
PosN           19
RRAe           10
PosA            8
RRNn            5
RRNe            2


### Ожидаемый результат:

```
        frequency
Norm         1162
Feedr          63
Artery         43
RRAn           26
PosN           19
RRAe           10
PosA            8
RRNn            5
RRNe            2
```

In [23]:
print(count_values(data=str_data,column=["Condition1","Condition2"]))

        frequency
Norm       1162.0
Feedr        63.0
Artery       43.0
RRAn         26.0
PosN         19.0
RRAe         10.0
PosA          8.0
RRNn          5.0
RRNe          2.0
Norm       1324.0
Feedr         5.0
RRNn          2.0
PosN          2.0
Artery        2.0
PosA          1.0
RRAe          1.0
RRAn          1.0


### Ожидаемый результат:

```
        frequency
Norm       1162.0
Feedr        63.0
Artery       43.0
RRAn         26.0
PosN         19.0
RRAe         10.0
PosA          8.0
RRNn          5.0
RRNe          2.0
Norm       1324.0
Feedr         5.0
Artery        2.0
PosN          2.0
RRNn          2.0
RRAn          1.0
RRAe          1.0
PosA          1.0
```

### Шаг 4

Пожалуйста, реализуйте функцию ```save_to_csv(имя файла, данные)```, которая будет экспортировать **непустой** ```DataFrame``` в csv-файл ```filename```. Обратите внимание на обработку ошибок входных аргументов.

In [ ]:
#Начало вашего кода
def save_to_csv(filename, data=pd.DataFrame()):
    if os.path.exists("{}.csv".format(filename)):
        return f"Error: {filename}.csv already exists, please try another file name"
    data.to_csv("{}.csv".format(filename))
    return f"{filename}.csv is created" 
#Конец вашего кода

In [ ]:
save_to_csv("House_Prices",str_data)

### Ожидаемый результат:

```
'Error: House_Prices.csv already exists, please try another file name'
```

In [ ]:
save_to_csv("str_house_prices",str_data)

### Ожидаемый результат:

```
'str_house_prices.csv is created'
```

In [ ]:
save_to_csv("num_house_prices",num_data)

### Ожидаемый результат:

```
'num_house_prices.csv is created'
```

In [ ]:
os.path.exists("num_house_prices.csv")

### Ожидаемый результат:

```
True
```

# Прекрасная работа!